// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfDUrJTsx89nnUIQ5CQHYBmlTAIIzL1jQ',
    appId: '1:1065948581417:web:d2ab80d88132ef773f1638',
    messagingSenderId: '1065948581417',
    projectId: 'spotify696967',
    authDomain: 'spotify696967.firebaseapp.com',
    storageBucket: 'spotify696967.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC51_6vupOe5VuJfxSoO-D-4jXIIXiAaRE',
    appId: '1:1065948581417:android:4a178c0da8e96dd33f1638',
    messagingSenderId: '1065948581417',
    projectId: 'spotify696967',
    storageBucket: 'spotify696967.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrXgFgxYS-omemeEI5QSEhR1QMbzT2lrs',
    appId: '1:1065948581417:ios:fee656b7844858e23f1638',
    messagingSenderId: '1065948581417',
    projectId: 'spotify696967',
    storageBucket: 'spotify696967.firebasestorage.app',
    iosBundleId: 'com.example.spotifyLike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrXgFgxYS-omemeEI5QSEhR1QMbzT2lrs',
    appId: '1:1065948581417:ios:fee656b7844858e23f1638',
    messagingSenderId: '1065948581417',
    projectId: 'spotify696967',
    storageBucket: 'spotify696967.firebasestorage.app',
    iosBundleId: 'com.example.spotifyLike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfDUrJTsx89nnUIQ5CQHYBmlTAIIzL1jQ',
    appId: '1:1065948581417:web:25a8f4f1e4575f6e3f1638',
    messagingSenderId: '1065948581417',
    projectId: 'spotify696967',
    authDomain: 'spotify696967.firebaseapp.com',
    storageBucket: 'spotify696967.firebasestorage.app',
  );
}
